/**
 * SmartSight App Strings
 * All app text content in one place for easy localization
 */

export const Strings = {
  app: {
    name: 'SmartSight',
    tagline: 'Your AI-powered eye health companion',
    description: 'Detect eye health issues early with AI-powered analysis',
  },
  common: {
    loading: 'Loading...',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    done: 'Done',
    next: 'Next',
    back: 'Back',
    skip: 'Skip',
    retry: 'Retry',
    share: 'Share',
    close: 'Close',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    error: 'Error',
    success: 'Success',
    warning: 'Warning',
    info: 'Info',
    tryAgain: 'Try Again',
  },
  onboarding: {
    welcome: 'Welcome to SmartSight',
    slide1: {
      title: 'Capture Eye Images',
      description: 'Take clear photos of your eyes using our guided camera interface',
    },
    slide2: {
      title: 'AI Analysis',
      description: 'Our advanced AI analyzes your images for potential eye health issues',
    },
    slide3: {
      title: 'Track Progress',
      description: 'Monitor your eye health over time with detailed history and insights',
    },
    getStarted: 'Get Started',
  },
  home: {
    title: 'Eye Health Dashboard',
    startTest: 'Start Eye Test',
    viewHistory: 'View History',
    lastTest: 'Last Test',
    noTests: 'No tests performed yet',
    quickActions: 'Quick Actions',
  },
  camera: {
    title: 'Take Photo',
    instructions: 'Position your eye within the circle and tap capture',
    capture: 'Capture',
    retake: 'Retake',
    usePhoto: 'Use Photo',
    permissionDenied: 'Camera permission is required to take photos',
    requestPermission: 'Grant Permission',
  },
  analysis: {
    title: 'Analyzing Image',
    analyzing: 'Analyzing...',
    pleaseWait: 'Please wait while we analyze your image',
    processing: 'Processing your image...',
    almostDone: 'Almost done...',
    preparing: 'Preparing results...',
    complete: 'Analysis Complete',
    prediction: 'Prediction',
    confidence: 'Confidence',
    viewDetails: 'View Details',
    retakePhoto: 'Retake Photo',
    step1: 'Processing image',
    step2: 'Running AI analysis',
    step3: 'Generating results',
    highConfidence: 'High confidence result',
    mediumConfidence: 'Medium confidence result',
    lowConfidence: 'Low confidence result',
  },
  results: {
    title: 'Analysis Results',
    healthy: 'Healthy',
    monitor: 'Monitor',
    critical: 'Requires Attention',
    confidence: 'Confidence',
    recommendation: 'Recommendation',
    recommendations: 'Recommendations',
    saveResult: 'Save Result',
    retakePhoto: 'Retake Photo',
    takeAnother: 'Take Another',
    viewHistory: 'View History',
    analysisComplete: 'Analysis Complete',
    technicalDetails: 'Technical Details',
    disclaimer: 'Important Notice',
    disclaimerText: 'This analysis is for informational purposes only and should not replace professional medical advice. Please consult with an eye care professional for proper diagnosis and treatment.',
    shareTitle: 'SmartSight Analysis Results',
    shareMessage: 'Check out my eye health analysis results from SmartSight!',
    generalRec1: 'Continue regular eye examinations with a qualified professional',
    generalRec2: 'Maintain good eye hygiene and protection from UV rays',
    generalRec3: 'Monitor any changes in vision and report to your eye doctor',
    lowConfidenceRec1: 'Consider retaking the photo with better lighting',
    lowConfidenceRec2: 'Ensure the camera lens is clean and focused',
    lowConfidenceRec3: 'Consult with an eye care professional for accurate assessment',
  },
  history: {
    title: 'Test History',
    empty: 'No test history available',
    emptyDescription: 'Start your first eye test to see results here',
    deleteConfirm: 'Are you sure you want to delete this test result?',
  },
  settings: {
    title: 'Settings',
    privacy: 'Privacy Policy',
    about: 'About',
    contact: 'Contact Support',
    clearHistory: 'Clear History',
    language: 'Language',
    notifications: 'Notifications',
    version: 'Version',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'Network error. Please check your connection.',
    camera: 'Camera error. Please try again.',
    analysis: 'Analysis failed. Please retake the photo.',
    analysisError: 'Analysis Error',
    analysisErrorMessage: 'Failed to analyze the image. Please try again.',
    storage: 'Storage error. Please try again.',
    permissions: 'Required permissions not granted.',
    shareError: 'Failed to share results',
  },
};