/**
 * SmartSight App Strings
 * All app text content in one place for easy localization
 */

export const Strings = {
  app: {
    name: 'SmartSight',
    tagline: 'AI-Powered Eye Health Analysis',
    description: 'Advanced eye health screening using artificial intelligence',
  },
  appName: 'SmartSight',
  common: {
    loading: 'Loading...',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    done: 'Done',
    next: 'Next',
    back: 'Back',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    close: 'Close',
    retry: 'Retry',
    skip: 'Skip',
    continue: 'Continue',
    share: 'Share',
    tryAgain: 'Try Again',
  },
  onboarding: {
    welcome: 'Welcome to SmartSight',
    title1: 'Advanced Eye Health Screening',
    description1: 'Use AI-powered technology to analyze your eye health quickly and accurately.',
    title2: 'Instant Results',
    description2: 'Get immediate insights about your eye condition with detailed recommendations.',
    title3: 'Track Your Health',
    description3: 'Monitor your eye health over time with comprehensive history tracking.',
    getStarted: 'Get Started',
    skip: 'Skip',
    next: 'Next',
  },
  home: {
    title: 'Eye Health Analysis',
    subtitle: 'Monitor your eye health with AI',
    startAnalysis: 'Start New Analysis',
    viewHistory: 'View History',
    lastAnalysis: 'Last Analysis',
    quickActions: 'Quick Actions',
    healthTip: 'Health Tip',
  },
  camera: {
    title: 'Camera',
    instruction: 'Position your eye within the circle and tap to capture',
    captureButton: 'Capture',
    retake: 'Retake',
    useImage: 'Use Image',
    permissionDenied: 'Camera permission is required to take photos for analysis.',
    permissionRequest: 'Grant Permission',
  },
  analysis: {
    title: 'Analyzing...',
    processingImage: 'Processing your image...',
    analyzingPatterns: 'Analyzing eye patterns...',
    generatingResults: 'Generating results...',
    prediction: 'Prediction',
    confidence: 'Confidence',
    recommendations: 'Recommendations',
    error: 'Analysis failed. Please try again.',
    highConfidence: 'High confidence - Results are very reliable',
    mediumConfidence: 'Medium confidence - Results are moderately reliable',
    lowConfidence: 'Low confidence - Consider retaking the photo for better results',
  },
  results: {
    title: 'Analysis Results',
    shareMessage: 'Check out my eye health analysis results from SmartSight!',
    analysisComplete: 'Analysis Complete',
    recommendations: 'Recommendations',
    technicalDetails: 'Technical Details',
    disclaimer: 'Medical Disclaimer',
    disclaimerText: 'This analysis is for informational purposes only and should not replace professional medical advice. Please consult with a healthcare provider for proper diagnosis and treatment.',
    takeAnother: 'Take Another Photo',
    viewHistory: 'View History',
    generalRec1: 'Continue regular eye check-ups with your healthcare provider',
    generalRec2: 'Maintain good eye hygiene and proper lighting when reading',
    generalRec3: 'Protect your eyes from UV rays with quality sunglasses',
    lowConfidenceRec1: 'Retake the photo in better lighting conditions',
    lowConfidenceRec2: 'Ensure the camera lens is clean and focused',
    lowConfidenceRec3: 'Position your eye clearly within the capture area',
    healthy: {
      title: 'Healthy Eye Detected',
      description: 'Your eye analysis shows normal, healthy patterns.',
      recommendations: [
        'Continue regular eye check-ups',
        'Maintain good eye hygiene',
        'Protect eyes from UV light',
      ],
    },
    monitor: {
      title: 'Monitor Recommended',
      description: 'Some patterns detected that may require monitoring.',
      recommendations: [
        'Schedule an eye examination within 2-4 weeks',
        'Monitor any changes in vision',
        'Avoid prolonged eye strain',
      ],
    },
    critical: {
      title: 'Immediate Attention Needed',
      description: 'Critical patterns detected that require immediate medical attention.',
      recommendations: [
        'Contact an eye care professional immediately',
        'Do not delay seeking medical attention',
        'Follow all medical advice strictly',
      ],
    },
    newAnalysis: 'New Analysis',
    viewDetails: 'View Details',
    saveResult: 'Save Result',
  },
  history: {
    title: 'Analysis History',
    empty: 'No analysis history yet',
    emptyMessage: 'Start your first eye health analysis to see results here.',
    delete: 'Delete Analysis',
    deleteConfirm: 'Are you sure you want to delete this analysis?',
  },
  settings: {
    title: 'Settings',
    notifications: 'Notifications',
    privacy: 'Privacy',
    about: 'About',
    version: 'Version',
    clearData: 'Clear All Data',
    clearDataConfirm: 'This will delete all your analysis history. Are you sure?',
  },
  errors: {
    generic: 'Something went wrong. Please try again.',
    network: 'Network error. Please check your connection.',
    camera: 'Camera error. Please try again.',
    analysis: 'Analysis failed. Please try again.',
    analysisError: 'Analysis Error',
    analysisErrorMessage: 'Unable to analyze the image. Please ensure good lighting and try again.',
    storage: 'Storage error. Please try again.',
    permissions: 'Required permissions not granted.',
    shareError: 'Share Error',
    tryAgain: 'Please try again later.',
  },
};

export default Strings;